feat: Edukaan Registration
tradeling/mobile-automation pull request #7
Opened 2022-04-06 15:38 UTC by Remon-Refaat

2022-04-06 16:53 UTC, harshprasad92 requested changes

2022-04-06 16:53 UTC, harshprasad92 commented on src/main/java/com/tradeling/mobile/driver/MobileActions.java
> -                    hideKeyboard();
@Remon-Refaat this will impact all buyer app test cases. We need to look something we can handle both the apps.
Also this should ideally not impact specifically to any application, should work generally.

2022-04-06 16:53 UTC, harshprasad92 commented on src/main/java/com/tradeling/mobile/pageObject/edukaanApp/EdukaanCommon.java
> +public class EdukaanCommon extends EnvironmentSetup {
Environment Setup class is only required to be extended for the test class.

2022-04-06 17:07 UTC, Remon-Refaat commented on src/main/java/com/tradeling/mobile/driver/MobileActions.java
> -                    hideKeyboard();
@harshprasad92 The Mobile Actions should handle only one action, it should be only Click or Send Keys or Get text for example. Also, it should be suitable for all apps, not only the buyer app. You can handle it like this:
![2022-04-06_21-02-42](https://user-images.githubusercontent.com/38832359/162029387-2b5d3145-b33f-4562-9ad6-9c6d24c73e67.jpg)

2022-04-06 17:09 UTC, Remon-Refaat commented on src/main/java/com/tradeling/mobile/pageObject/edukaanApp/EdukaanCommon.java
> +public class EdukaanCommon extends EnvironmentSetup {
@harshprasad92 Why it is only required to be extended for the test class. We can inherit any class from any class unless this will not affect the script or the framework.

2022-04-06 17:19 UTC, harshprasad92 commented on src/main/java/com/tradeling/mobile/pageObject/edukaanApp/EdukaanCommon.java
> +public class EdukaanCommon extends EnvironmentSetup {
Agree to this, but i cannot find any use of this extension in this class. Also We have created EnvironmentSteup class in the framework to handle the test initialisation. Just to have a standard approach across the projects this should be avoided.

2022-04-06 17:29 UTC, Remon-Refaat commented on src/main/java/com/tradeling/mobile/pageObject/edukaanApp/EdukaanCommon.java
> +public class EdukaanCommon extends EnvironmentSetup {
@harshprasad92 
1- Regarding the use of this extend, you can have a look at the following screenshot:
![2022-04-06_21-21-51](https://user-images.githubusercontent.com/38832359/162032368-3d792c15-1ddc-481d-ada4-5e10615e24fd.jpg)
2- Regarding the standard approach, we can follow this if it will not affect our script but in our case, we need to differentiate between ios and android in page object classes themselves not in the test cases. The test cases are supposed to be just call for the methods we created and add the value of the parameters.

2022-04-07 06:31 UTC, Remon-Refaat commented
@harshprasad92 The changes, we agreed on, are done.

2022-04-07 06:32 UTC, harshprasad92 approved these changes

2022-04-07 10:49 UTC, MohmedEmad approved these changes

2022-04-07 10:49 UTC, merged