feat: Add device type to the command line
tradeling/mobile-automation pull request #8
Opened 2022-04-07 17:34 UTC by Remon-Refaat

- Change the project to get the device type from the command line.
- Now you can use like this command to run the project:
mvn clean test -Pedukaan -Denvironment=local -DdeviceType=android -DappPath=/Users/remonrefaat/Desktop/Tradeling/Project
- You can run ios and android at the same time as shown in the following video:

https://user-images.githubusercontent.com/38832359/162262346-96b9cef0-dbee-4b68-820b-fad6dcbe66be.mp4

2022-04-08 05:16 UTC, MohmedEmad approved these changes
Big Claps @Remon-Refaat 👏

2022-04-08 05:59 UTC, harshprasad92 requested changes
This is good, seems we need to trigger two different executions one for ios and one for android for executing in parallel or sequential.
Can we still explore some ways where we can have one execution for both android and ios.
We can add listeners from testng to do so
Please have a look at below, we can achieve passing both platform in single execution and also the parallel is also acheivable: https://developers.perfectomobile.com/display/TT/Run+a+specific+test+by+test+name+in+the+testng.xml+file

2022-04-14 05:32 UTC, MohmedEmad commented
@harshprasad92 If this will take time to implement, we can consider it later

2022-04-14 05:56 UTC, harshprasad92 approved these changes

2022-04-18 07:02 UTC, merged